credentials:
  artifactory:
    prod:
      credentialsId: svc-artifactory
      url: https://artifactory.ccta.dk
  openshift:
    dev:
      credentialsId: ocpt-deployer-token-ejendomsdata-dev
      url: https://ocpt.ccta.dk:8443
      namespace: ejendomsdata-dev
    test:
      credentialsId: jenkins-k8s-api-token
      url: https://ocpt.ccta.dk:8443
      namespace: ejendomsdata-test
    prod:
      credentialsId: jenkins-k8s-api-token
      url: https://ocp.ccta.dk:8443
      namespace: ejendomsdata
  github:
    prod:
      credentialsId: svc-github-service-user
      url: https://github.ccta.dk
  apm:
    prod:
      url: https://apm.sheplog.ccta.dk
      stream: apm-ufst_ejendomsdata_apm_debug_nprod
  sonarqube:
    prod:
      credentialsId: svc-sonarqube-token
configuration:
  build:
    branchPatterns:
      releaseBranch: "release\\/\\d{1,3}\\.\\d{1,3}(\\.\\d{1,3})?"
      releaseTag: "v\\d{1,3}\\.\\d{1,3}(\\.\\d{1,3})?"
      releaseCandidateTag: "^\\d{1,3}\\.\\d{1,3}(\\.\\d{1,3})?(-rc-\\d{1,2})?"
      pullRequestPattern: "PR-\\d{1,5}"
      featurePattern: "feature\\/.+"
      bugfixPattern: "bugfix\\/.+"
    retention: 5
  deployment:
    dev:
      urlPostfix: ocpt.ccta.dk
      replicas: 1
    test:
      urlPostfix: ocpt.ccta.dk
      replicas: 1
    prod:
      urlPostfix: ocp.ccta.dk
      replicas: 2
  release:
    fluxcdRepo: ejendomsdata/edp-prod-config
    jiraIssuePattern: EPL-([0-9]+)
  tools:
    artifactory:
      serverId: artifactory.ccta.dk
      deployer:
        releaseRepo: ejendomsdata-maven-local
        snapshotRepo: ejendomsdata-maven-local
      resolver:
        releaseRepo: ejendomsdata-maven-virtual
        snapshotRepo: ejendomsdata-maven-virtual
      sonarqube:
        projectKey: ejendomsdata.edp-ork-ejendom-med-beliggenhedsadresse
        prod:
          name: "sonarqube.ocp.ccta.dk"
    maven:
      name: "Maven 3.6"
    java:
      name: JDK11
  service:
    healthcheckPath: 'actuator/health'
